modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="questadmin"
version="${version}"
displayName="QuestAdmin"
authors="nobu0707"
description='''Quest management mod for Forge servers using Lightman's Currency rewards.'''

[[dependencies.questadmin]]
    modId="lightmanscurrency"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
